version: "3.1"
services:
  proxy:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
    depends_on:
      - projekt
      - person

  # ========================================
  # Falls Sie das Person-SCS implementieren,
  # überschreiben Sie diesen Teil
  person:
    image: grvid100/person-scs
    environment:
      - DATABASE_HOST=persondb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=personen
    depends_on:
      - persondb

  persondb:
   image: mysql:latest
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=personen
     - MYSQL_PASSWORD=root
   volumes:
     - ./datavolume_person:/var/lib/mysql

  # ========================================
  # Falls Sie das Projekt-SCS implementieren,
  # überschreiben Sie diesen Teil
  projekt:
    build: projekt-scs
    environment:
      - DATABASE_HOST=projektdb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=lamborghini
      - DATABASE_NAME=projektdb
    depends_on:
      - projektdb

  projektdb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=lamborghini
      - MYSQL_DATABASE=projektdb
      - MYSQL_PASSWORD=lamborghini
    volumes:
      - ./projekt-scs/data:/var/lib/mysql
  # ========================================
